/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoterRouteImport } from './routes/voter'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreatorIndexRouteImport } from './routes/creator.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CreatorSecretIdsRouteImport } from './routes/creator.secret-ids'
import { Route as CreatorResultsRouteImport } from './routes/creator.results'
import { Route as CreatorElectionsRouteImport } from './routes/creator.elections'
import { Route as CreatorCandidatesRouteImport } from './routes/creator.candidates'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as ElectionsIdVoteRouteImport } from './routes/elections.$id.vote'
import { Route as ElectionsIdResultsRouteImport } from './routes/elections.$id.results'
import { Route as CreatorElectionsNewRouteImport } from './routes/creator.elections.new'

const VoterRoute = VoterRouteImport.update({
  id: '/voter',
  path: '/voter',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorIndexRoute = CreatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CreatorSecretIdsRoute = CreatorSecretIdsRouteImport.update({
  id: '/secret-ids',
  path: '/secret-ids',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorResultsRoute = CreatorResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorElectionsRoute = CreatorElectionsRouteImport.update({
  id: '/elections',
  path: '/elections',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorCandidatesRoute = CreatorCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => CreatorRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const ElectionsIdVoteRoute = ElectionsIdVoteRouteImport.update({
  id: '/elections/$id/vote',
  path: '/elections/$id/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsIdResultsRoute = ElectionsIdResultsRouteImport.update({
  id: '/elections/$id/results',
  path: '/elections/$id/results',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorElectionsNewRoute = CreatorElectionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CreatorElectionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/audit': typeof AuditRoute
  '/creator': typeof CreatorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/voter': typeof VoterRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/creator/candidates': typeof CreatorCandidatesRoute
  '/creator/elections': typeof CreatorElectionsRouteWithChildren
  '/creator/results': typeof CreatorResultsRoute
  '/creator/secret-ids': typeof CreatorSecretIdsRoute
  '/admin/': typeof AdminIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/creator/elections/new': typeof CreatorElectionsNewRoute
  '/elections/$id/results': typeof ElectionsIdResultsRoute
  '/elections/$id/vote': typeof ElectionsIdVoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/voter': typeof VoterRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/creator/candidates': typeof CreatorCandidatesRoute
  '/creator/elections': typeof CreatorElectionsRouteWithChildren
  '/creator/results': typeof CreatorResultsRoute
  '/creator/secret-ids': typeof CreatorSecretIdsRoute
  '/admin': typeof AdminIndexRoute
  '/creator': typeof CreatorIndexRoute
  '/creator/elections/new': typeof CreatorElectionsNewRoute
  '/elections/$id/results': typeof ElectionsIdResultsRoute
  '/elections/$id/vote': typeof ElectionsIdVoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/audit': typeof AuditRoute
  '/creator': typeof CreatorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/voter': typeof VoterRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/creator/candidates': typeof CreatorCandidatesRoute
  '/creator/elections': typeof CreatorElectionsRouteWithChildren
  '/creator/results': typeof CreatorResultsRoute
  '/creator/secret-ids': typeof CreatorSecretIdsRoute
  '/admin/': typeof AdminIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/creator/elections/new': typeof CreatorElectionsNewRoute
  '/elections/$id/results': typeof ElectionsIdResultsRoute
  '/elections/$id/vote': typeof ElectionsIdVoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audit'
    | '/creator'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/voter'
    | '/admin/approvals'
    | '/admin/audit'
    | '/creator/candidates'
    | '/creator/elections'
    | '/creator/results'
    | '/creator/secret-ids'
    | '/admin/'
    | '/creator/'
    | '/creator/elections/new'
    | '/elections/$id/results'
    | '/elections/$id/vote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/voter'
    | '/admin/approvals'
    | '/admin/audit'
    | '/creator/candidates'
    | '/creator/elections'
    | '/creator/results'
    | '/creator/secret-ids'
    | '/admin'
    | '/creator'
    | '/creator/elections/new'
    | '/elections/$id/results'
    | '/elections/$id/vote'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audit'
    | '/creator'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/voter'
    | '/admin/approvals'
    | '/admin/audit'
    | '/creator/candidates'
    | '/creator/elections'
    | '/creator/results'
    | '/creator/secret-ids'
    | '/admin/'
    | '/creator/'
    | '/creator/elections/new'
    | '/elections/$id/results'
    | '/elections/$id/vote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuditRoute: typeof AuditRoute
  CreatorRoute: typeof CreatorRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VoterRoute: typeof VoterRoute
  ElectionsIdResultsRoute: typeof ElectionsIdResultsRoute
  ElectionsIdVoteRoute: typeof ElectionsIdVoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voter': {
      id: '/voter'
      path: '/voter'
      fullPath: '/voter'
      preLoaderRoute: typeof VoterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/': {
      id: '/creator/'
      path: '/'
      fullPath: '/creator/'
      preLoaderRoute: typeof CreatorIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/creator/secret-ids': {
      id: '/creator/secret-ids'
      path: '/secret-ids'
      fullPath: '/creator/secret-ids'
      preLoaderRoute: typeof CreatorSecretIdsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/results': {
      id: '/creator/results'
      path: '/results'
      fullPath: '/creator/results'
      preLoaderRoute: typeof CreatorResultsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/elections': {
      id: '/creator/elections'
      path: '/elections'
      fullPath: '/creator/elections'
      preLoaderRoute: typeof CreatorElectionsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/candidates': {
      id: '/creator/candidates'
      path: '/candidates'
      fullPath: '/creator/candidates'
      preLoaderRoute: typeof CreatorCandidatesRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/elections/$id/vote': {
      id: '/elections/$id/vote'
      path: '/elections/$id/vote'
      fullPath: '/elections/$id/vote'
      preLoaderRoute: typeof ElectionsIdVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections/$id/results': {
      id: '/elections/$id/results'
      path: '/elections/$id/results'
      fullPath: '/elections/$id/results'
      preLoaderRoute: typeof ElectionsIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/elections/new': {
      id: '/creator/elections/new'
      path: '/new'
      fullPath: '/creator/elections/new'
      preLoaderRoute: typeof CreatorElectionsNewRouteImport
      parentRoute: typeof CreatorElectionsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CreatorElectionsRouteChildren {
  CreatorElectionsNewRoute: typeof CreatorElectionsNewRoute
}

const CreatorElectionsRouteChildren: CreatorElectionsRouteChildren = {
  CreatorElectionsNewRoute: CreatorElectionsNewRoute,
}

const CreatorElectionsRouteWithChildren =
  CreatorElectionsRoute._addFileChildren(CreatorElectionsRouteChildren)

interface CreatorRouteChildren {
  CreatorCandidatesRoute: typeof CreatorCandidatesRoute
  CreatorElectionsRoute: typeof CreatorElectionsRouteWithChildren
  CreatorResultsRoute: typeof CreatorResultsRoute
  CreatorSecretIdsRoute: typeof CreatorSecretIdsRoute
  CreatorIndexRoute: typeof CreatorIndexRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorCandidatesRoute: CreatorCandidatesRoute,
  CreatorElectionsRoute: CreatorElectionsRouteWithChildren,
  CreatorResultsRoute: CreatorResultsRoute,
  CreatorSecretIdsRoute: CreatorSecretIdsRoute,
  CreatorIndexRoute: CreatorIndexRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuditRoute: AuditRoute,
  CreatorRoute: CreatorRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VoterRoute: VoterRoute,
  ElectionsIdResultsRoute: ElectionsIdResultsRoute,
  ElectionsIdVoteRoute: ElectionsIdVoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
